- .gitignore
- relenv/build/__init__.py
- relenv/build/common.py
- relenv/build/windows.py
- relenv/common.py
- tests/test_build.py
Also fixes typo `recipies` => `recipes`
> Add ability to set python version on Windows

- .github/workflows/build-action.yml
- .github/workflows/ci.yml
- .github/workflows/deploy-build-action.yml
- .github/workflows/deploy-package-action.yml
- .github/workflows/deploy-toolchain-action.yml
- .github/workflows/pr.yml
- .github/workflows/release.yml
- .github/workflows/test-action.yml
- .github/workflows/toolchain-action.yml
- docs/source/index.rst
- relenv/common.py
- Fix tag permissions
- Fix package push condition
- Ensure build and toolchain directories exist
> Fix issues in release pipeline

- relenv/build/common.py
- relenv/common.py
- relenv/runtime.py
- tests/test_verify_build.py
> Fix issues when installing in environment using usersite packages.

- .github/workflows/build-action.yml
> Debug mac environment

- relenv/build/common.py
- relenv/common.py
- relenv/toolchain.py
Signed-off-by: Pedro Algarvio <palgarvio@vmware.com>
> Always report what's getting downloaded and to where

- relenv/build/common.py
Signed-off-by: Pedro Algarvio <palgarvio@vmware.com>
> Support virtualenvs(with --system-site-packages) from relenv

- tests/test_verify_build.py
Test for this: https://github.com/saltstack/relative-environment-for-python/pull/53
> Add test for nox virtualenvs

- relenv/build/windows.py
This is what we're currently building
> Update Python to 3.8.15 for Windows

- relenv/__main__.py
Signed-off-by: Pedro Algarvio <palgarvio@vmware.com>
> Allow the `relenv` CLI to report it's version.

- relenv/common.py
- tests/test_verify_build.py
> Fix symlinks for oses that don't have coreutils

- .github/workflows/build-action.yml
- .github/workflows/deploy-build-action.yml
- relenv/__main__.py
- relenv/build/__init__.py
- relenv/build/common.py
- relenv/build/darwin.py
- relenv/build/linux.py
- relenv/build/windows.py
- relenv/common.py
- relenv/create.py
- relenv/fetch.py
- relenv/runtime.py
- tests/test_build.py
This work still needs a fair amount of re-factoring but it's a start. Commiting it now so we can get some testing going.
> Initial commit of multiple python versions

- relenv/build/common.py
- relenv/build/darwin.py
- relenv/build/linux.py
- relenv/build/windows.py
> Add libxcrypt to linux builds

- .github/workflows/test-action.yml
- relenv/__init__.py
- relenv/build/common.py
- relenv/common.py
- relenv/runtime.py
- setup.cfg
- tests/test_common.py
shellcheck results. minor changes around the formatting. no functionality change. although it should now be able to handle spaces. 
fix for https://github.com/saltstack/salt/issues/63517
> shellcheck results

- .github/workflows/build-action.yml
- .github/workflows/pre-commit-action.yml
- relenv/build/common.py
- relenv/build/windows.py
- relenv/runtime.py
- setup.cfg
- tests/test_verify_build.py
> Better handleing of packaged c extensions

- .github/workflows/build-native-action.yml
- .github/workflows/deploy-build-action.yml
- relenv/build/common.py
- relenv/runtime.py
- tests/test_verify_build.py
- Add cargo config to toolchain directory when bootstraping if needed
- Set CARGO_HOME to toolchain directory when building wheels
- fix #92
- Add sys.RELENV which is set to the relenv root directory. fixes #90
> Cargo config

- relenv/build/common.py
- relenv/relocate.py
- relenv/runtime.py
- tests/test_verify_build.py
This works around the limitations reported to cryptography https://github.com/pyca/cryptography/issues/8614
> Support and test cryptography 40.0.1

- relenv/buildenv.py
Fix the output from buildenv to ensure there are no newlines.
> Fix the output from buildenv to ensure there are no newlines.

- docs/source/additional-dependencies.rst
- tests/test_verify_build.py
Update the documentation and tests to use source when setting up the ENV varaiables rather than eval.
>  Swap source for eval

- relenv/common.py
- relenv/runtime.py
- tests/test_common.py
- tests/test_verify_build.py
> Fix shebangs and pkg uninstall when using target argument with pip

- .github/workflows/ci.yml
- .github/workflows/deploy-build-action.yml
- .github/workflows/deploy-toolchain-action.yml
- .github/workflows/release.yml
- relenv/common.py
- tests/test_verify_build.py
Fixes: https://github.com/saltstack/relative-environment-for-python/issues/129
> Publish builds and toolchains to repo.saltproject.io

- .github/workflows/build-cross-action.yml
- .github/workflows/build-native-action.yml
- .github/workflows/deploy-build-action.yml
- relenv/build/common.py
- relenv/build/darwin.py
- relenv/build/linux.py
- relenv/build/windows.py
- relenv/fetch.py
- tests/test_verify_build.py
Bumping python minor version. 
This gives us the latest openssl 1.1.1u on Windows.
> Update minor version of python

- .github/workflows/ci.yml
- .github/workflows/test-fips-action.yml
- relenv/runtime.py
- tests/conftest.py
- tests/test_fips_photon.py
- tests/test_verify_build.py
#149 - Load the system's fips provider before relenv default and legacy providers.
> Fix openssl when fips is used

- relenv/build/darwin.py
- relenv/build/linux.py
> Bump openssl and sqlite versions

- relenv/runtime.py
- tests/test_verify_build.py
> Fixes for running debugpy

- .github/workflows/build-cross-action.yml
- .github/workflows/build-native-action.yml
- .github/workflows/deploy-build-action.yml
- .github/workflows/test-fips-action.yml
- relenv/build/common.py
- relenv/build/darwin.py
- relenv/build/linux.py
- relenv/build/windows.py
- tests/test_verify_build.py
Python Upgrades:
3.10.14
3.11.8
Dependency Version Upgrades
openssl 3.2.1
sqlite 3450200
libffi 3.4.6
zlib 1.3.1
> Upgrade python and dependencies

- .github/workflows/build-native-action.yml
- relenv/runtime.py
- tests/test_verify_build.py
Fix #182 
Only patch 'get_scheme' during installation of package and requirements. Do not patch `get_scheme` while installing build dependencies into build environment.
> Fix mysqlclient, libvirt-python, M2crypto target installation

- relenv/runtime.py
- tests/test_verify_build.py
Scheme objects are now frozen. Make a new one and return it.
Fixes #186
> Fix pip target with latest pip

- .github/workflows/build-cross-action.yml
- .github/workflows/build-native-action.yml
- .github/workflows/deploy-build-action.yml
- .github/workflows/github-release.yml
- .github/workflows/test-fips-action.yml
- CHANGELOG.md
- relenv/build/darwin.py
- relenv/build/linux.py
- relenv/build/windows.py
* Update python 3.10 to 3.10.17
* Update python 3.13 to 3.13.3
* Update libxcrypt to 4.4.38
* Update gdbm to 1.25
> Include newer versions
